name: Build Documentation

on:
  push:
    branches:
      - testing

jobs:
  build_docs:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.0

      - name: ⚙️ Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v2.4.0
        with:
          auto-update-conda: true
          activate-environment: mle-dev
          environment-file: env.yml
          use-mamba: true
          miniconda-version: "latest"
          minconda-download-url: "https://your-custom-mirror.com/miniconda"  

      - name: Install tree command
        run: sudo apt-get install tree

      - name: Clean old HTML files
        run: |
          rm -rf docs/build/html/*

      - name: Build docs using Sphinx
        run: |
          sphinx-build -b html docs/source docs/build/html
